/* ── aurora palettes ───────────────────────────────────────
 * Every sub-variant is defined by ONE number — its base HUE. All other axes
 * are SHARED constants applied identically to every palette, so the variants
 * are normalized, not hand-tuned:
 *
 *   • Saturation — locked (SAT) for all.
 *   • Hue fan    — 2 stops sit at the base hue (the "boring" semantic color);
 *                  1 stop is fanned by HUE_FAN° toward its neighbour (the
 *                  "cute" accent: green→lime, magenta→coral, blue→aqua…).
 *                  Same fan for every palette → the cute color is generated by
 *                  the same proportion, never hardcoded.
 *   • Lightness  — two levels (LIGHT_L / DARK_L). The 2:1 split FLIPS with the
 *                  theme: light mode = 2 light + 1 dark, dark mode = 2 dark +
 *                  1 light. Same values, mirrored ratio.
 *
 * So a palette = { hue }, and buildPalette(hue, isDark) emits the 3 stops. */

export type AuroraPalette =
    | 'primary'
    | 'success'
    | 'warning'
    | 'danger'
    | 'info'
    | 'neutral'
    | 'pink'
    | 'sunshine'
    | 'sky';

/** Each palette's base hue (degrees on the color wheel). The ONLY per-palette
 *  value — everything else is shared. */
export const AURORA_HUES: Record<AuroraPalette, number> = {
    danger: 5,        // pure red centre — symmetric fan gives coral + pink sides
    sunshine: 42,     // warm orange centre — fan gives red-orange + gold (no green)
    warning: 42,      // same family as sunshine (amber/orange)
    success: 130,     // green centre — fan gives lime + teal (stays off blue)
    sky: 195,
    info: 220,
    primary: 250,
    pink: 330,
    neutral: 220,   // saturation is forced low for neutral (see SAT_FOR)
};

// ── Shared, normalized axes ──
const SAT = 90;          // % — locked saturation for every palette
const NEUTRAL_SAT = 8;   // neutral is the one low-chroma palette
const HUE_FAN = 40;      // ° — SYMMETRIC fan: stops sit at base−fan, base, base+fan
const LIGHT_L = 70;      // % — the "light" lightness level (clearly light)
const DARK_L = 32;       // % — the "dark" lightness level (genuinely deep)

const satFor = (p: AuroraPalette) => (p === 'neutral' ? NEUTRAL_SAT : SAT);
const hsl = (h: number, s: number, l: number) => `hsl(${((h % 360) + 360) % 360} ${s}% ${l}%)`;

const ANCHOR_L = 55;     // % — lightness of the immutable anchor stop

/** The ANCHOR color of a palette: its pure, immutable identity hue
 *  (success=green, danger=red, info=blue). No fan, no theme flip, fixed
 *  lightness — it always reads as the value the variant represents. */
export const anchorColor = (p: AuroraPalette): string =>
    hsl(AURORA_HUES[p], satFor(p), ANCHOR_L);

/** Build a palette's stops: the immutable ANCHOR (identity hue) plus 3
 *  generated stops fanned SYMMETRICALLY around the base — [base−fan, base,
 *  base+fan] — so their average hue equals the base (no drift: red reads red,
 *  green reads green) while giving two candy neighbours (success → lime AND
 *  teal). hue (identity) and fan (spread) are orthogonal; one shared fan works
 *  for all. The 3 generated stops' lightness 2:1 split flips with theme —
 *  light: L,L,D / dark: D,D,L (minority lands on the centre stop). The anchor
 *  stays put regardless, so the value is always present. */
export function buildPalette(p: AuroraPalette, isDark: boolean): string[] {
    const h = AURORA_HUES[p];
    const s = satFor(p);
    // 4 DISTINCT stops on one hue family, ordered light → dark with rising
    // vibrancy as they deepen (the "bulb )) " read: a light airy volume, then a
    // more vibrant deep volume). Each stop has its OWN lightness so they don't
    // collapse into 2. The hue fans only on the lighter pair (clean bright
    // mixing); the deeper pair holds the base hue (no muddy cross-hue darks).
    // Theme flips the whole band darker/lighter but keeps the 4 distinct.
    const shift = isDark ? -10 : 0;            // dark theme: deepen the whole band
    // Sunshine's inner wave reads better as a soft pale yellow — pull its
    // lightest stop lighter + less saturated than the shared default.
    const innerSat = p === 'sunshine' ? s - 28 : s - 8;
    const innerL = p === 'sunshine' ? 80 : 74;
    return [
        hsl(h - HUE_FAN, innerSat, innerL + shift),  // 1 lightest, airy
        hsl(h - HUE_FAN * 0.4, s, 62 + shift),       // 2 light, on the cute side
        hsl(h, s, 48 + shift),                       // 3 vibrant mid — the identity
        hsl(h + HUE_FAN * 0.3, s, 34 + shift),       // 4 deep vibrant — the dark volume
    ];
}

export const AURORA_PALETTE_IDS = Object.keys(AURORA_HUES) as AuroraPalette[];
